version: 0.2

phases:
  pre_build:
    commands:
      - node -v
      - npm install -g yarn
  build:
    commands:
      - yarn install
      - yarn build:dev
artifacts:
  files:
    - '**/*'
  base-directory: dist